import type {Metadata} from "next";
import {redirect} from "next/navigation";
import {isAdmin} from "@/lib/security";
import {db,bucket} from "@/lib/supabase";
import {statuses} from "@/lib/schema";
import {artists,getArtistById} from "@/lib/content";
export const dynamic="force-dynamic";
export const metadata:Metadata={title:"Lead inbox",robots:{index:false,follow:false}};
export default async function Admin({searchParams}:{searchParams:Promise<{page?:string}>}){if(!await isAdmin())redirect("/admin/login");const p=await searchParams;const page=Math.max(0,Math.min(10000,Number(p.page)||0));const client=db();const {data:leads,error}=await client.from("project_requests").select("*,request_images(*)",{count:"exact"}).order("created_at",{ascending:false}).range(page*25,page*25+24);if(error)return <section className="section admin"><h1>Lead inbox</h1><p role="alert">The inbox could not be loaded. Check the database connection and migration.</p></section>;
return <section className="section admin"><div className="admin-header"><div><p className="eyebrow">Lead inbox</p><h1>Incoming projects.</h1></div><form action="/api/admin/logout" method="post"><button className="button secondary">Sign out</button></form></div>{!leads?.length&&<p>No requests on this page yet.</p>}{await Promise.all((leads||[]).map(async lead=>{const photos=await Promise.all((lead.request_images as {id:string;image_url:string;image_type:string}[]).map(async photo=>{const {data}=await client.storage.from(bucket).createSignedUrl(photo.image_url,3600);return {...photo,url:data?.signedUrl}}));return <details key={lead.id} className="admin-lead"><summary><strong>{lead.customer_name}</strong><span>{lead.city}, {lead.state}</span><span>{lead.status}</span><span>{new Date(lead.created_at).toLocaleDateString("en-US")}</span></summary><dl>{artists.length>1&&<><dt>Artist</dt><dd>{getArtistById(lead.assigned_artist_id)?.name??"Unassigned"}</dd></>}<dt>Email</dt><dd><a href={`mailto:${lead.customer_email}`}>{lead.customer_email}</a></dd><dt>Phone</dt><dd>{lead.customer_phone?<a href={`tel:${lead.customer_phone}`}>{lead.customer_phone}</a>:"Not provided"}</dd><dt>Preferred contact</dt><dd>{lead.preferred_contact}</dd><dt>Location</dt><dd>{lead.city}, {lead.state} {lead.zip} · {lead.indoor_outdoor}</dd><dt>Dimensions</dt><dd>{lead.wall_dimensions_unknown?"Unknown":`${lead.wall_width} × ${lead.wall_height} ${lead.wall_units}`}</dd><dt>Material</dt><dd>{lead.wall_material||"Unknown"}</dd><dt>Wall notes</dt><dd>{lead.wall_notes||"None"}</dd><dt>Idea</dt><dd>{lead.description}</dd><dt>Project type</dt><dd>{lead.project_type}</dd><dt>Budget</dt><dd>{lead.budget_range||"Not provided"}</dd><dt>Timeline</dt><dd>{lead.timeline}</dd><dt>Email notification</dt><dd>{lead.notification_status}{lead.notification_status!=="sent"&&" — review this lead directly; email was not confirmed."}</dd></dl><div className="photo-grid">{photos.map(x=><figure key={x.id}>{x.url?<a href={x.url} target="_blank" rel="noopener noreferrer"><img src={x.url} alt={`Submitted ${x.image_type} photo`}/></a>:<p>Photo unavailable</p>}<figcaption>{x.image_type}</figcaption></figure>)}</div><form action="/api/admin/status" method="post"><input type="hidden" name="id" value={lead.id}/><label htmlFor={`status-${lead.id}`} className="sr-only">Lead status</label><select id={`status-${lead.id}`} name="status" defaultValue={lead.status}>{statuses.map(x=><option key={x}>{x}</option>)}</select><button className="button">Update status</button></form></details>}))}<div className="form-actions">{page>0&&<a href={`/admin?page=${page-1}`}>Previous page</a>}{leads?.length===25&&<a href={`/admin?page=${page+1}`}>Next page</a>}</div></section>}
