import Link from "next/link";
import {site,primaryArtist as a,projectsBy} from "@/lib/content";
import {CTA,FinalCTA,ProjectCard} from "@/components/shell";
const services:[string,string][]=[["Commercial","/commercial-murals"],["Residential","/residential-murals"],["Public art","/public-art"],["Restaurants & hospitality","/request"],["Schools & organizations","/request"],["Something custom","/request"]];
const steps:[string,string][]=[[`Show ${a.firstName} your wall`,"A few photos from different angles."],["Share your idea","Rough is fine. Inspiration helps."],[`${a.firstName} reviews it`,"Space, scope, surface, and access."],["Concept & quote","Agree on a direction and a price."],["Paint day","The wall becomes a place."]];
export default function Home(){return <>
<section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="tiny-star" aria-hidden="true">✳</span> A wall is just the beginning.</p><h1>Transform your wall into something people <em>remember.</em></h1><div className="hero-bottom"><p>{site.subheading}</p><div className="hero-actions"><CTA/><Link className="text-link" href="#work">See the work <span aria-hidden="true">↓</span></Link></div></div></div><figure className="hero-image"><img src={site.heroImage.src} alt={site.heroImage.alt} fetchPriority="high" width={site.heroImage.width} height={site.heroImage.height}/><figcaption><span>Art that changes a place.</span><span>Greetings from Cumberland / Maryland</span></figcaption></figure></section>
<section className="section work" id="work"><div className="section-heading"><div><p className="eyebrow">01 / Selected work</p><h2>Walls with<br/>something to say.</h2></div><p>A sense of place. A little personality.<br/>A reason to stop and look.</p></div><div className="portfolio">{projectsBy(a.id).filter(p=>p.featured).map(project=><ProjectCard key={project.slug} project={project}/>)}</div></section>
<section className="section services"><p className="eyebrow">02 / What {a.firstName} paints</p><div className="services-layout"><h2>Your space.<br/>Your story.<br/><em>Painted big.</em></h2><div>{services.map(([x,href],i)=><Link href={href} key={x}><span className="service-number">0{i+1}</span>{x}<span aria-hidden="true">↗</span></Link>)}</div></div></section>
<section className="wall-cta"><div><p className="eyebrow">The best starting point? Your wall.</p><h2>Have a<br/>blank wall?</h2><p>Send {a.firstName} a photo of your space and share what you’re imagining. Measurements are optional.</p><CTA/></div><div className="wall-outline" aria-hidden="true"><span className="dim dim-w">W ?</span><span className="dim dim-h">H ?</span><span className="wall-plus">+</span><p>A little vision.<br/>A lot of possibility.</p><span className="wall-caption">Your next favorite place</span></div></section>
<section className="section process"><div className="section-heading"><div><p className="eyebrow">03 / From wall to wow</p><h2>Let’s make it happen.</h2></div><p>No perfect brief needed.<br/>Just a wall and a starting point.</p></div><ol>{steps.map(([x,d],i)=><li key={x}><span>0{i+1}</span><div><h3>{x}</h3><p>{d}</p></div></li>)}</ol></section>
<section className="section area"><p className="eyebrow">04 / Rooted here. Open to what’s next.</p><div className="area-layout"><h2>{a.region}<br/><em>& a little beyond.</em></h2><div><p>Custom murals for spaces across {a.region} and nearby regions. Projects farther afield are considered based on scope and availability.</p><div className="places">{a.serviceAreas.map(x=><span key={x}>{x}</span>)}</div><p className="muted">{a.serviceAreaNote}</p><CTA>Tell {a.firstName} where your wall is</CTA></div></div></section>
<section className="section about-preview">{a.profileImage?<figure className="portrait"><img src={a.profileImage} alt={`${a.name}, ${a.role.toLowerCase()}`} loading="lazy" style={{objectPosition:a.portraitFocus}}/><figcaption>{a.name} / {a.region}</figcaption></figure>:<blockquote><span aria-hidden="true">“</span>Good walls deserve <em>good stories.</em></blockquote>}<div><p className="eyebrow">05 / The artist behind the wall</p><h2>Meet {a.firstName}.</h2><p>{a.bio}</p><Link className="text-link" href="/about">More about {a.firstName} <span aria-hidden="true">↗</span></Link></div></section><FinalCTA/>
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"Person",name:a.name,jobTitle:a.role,url:site.url,homeLocation:{"@type":"Place",name:a.region}}).replace(/</g,"\\u003c")}}/>
</>}
