import Link from "next/link";
import {site} from "@/lib/content";
import {CTA,FinalCTA} from "@/components/shell";
const services:[string,string][]=[["Commercial","/commercial-murals"],["Residential","/residential-murals"],["Public art","/public-art"],["Restaurants & hospitality","/request"],["Schools & organizations","/request"],["Something custom","/request"]];
const steps:[string,string][]=[["Show Marc your wall","A few photos from different angles."],["Share your idea","Rough is fine. Inspiration helps."],["Marc reviews it","Space, scope, surface, and access."],["Concept & quote","Agree on a direction and a price."],["Paint day","The wall becomes a place."]];
export default function Home(){return <>
<section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="tiny-star" aria-hidden="true">✳</span> A wall is just the beginning.</p><h1>Transform your wall into something people <em>remember.</em></h1><div className="hero-bottom"><p>{site.subheading}</p><div className="hero-actions"><CTA/><Link className="text-link" href="#work">See the work <span aria-hidden="true">↓</span></Link></div></div></div><figure className="hero-image"><img src={site.heroImage} alt="Greetings from Cumberland mural by Marc Phillips, with local landmarks and businesses illustrated inside large postcard-style letters" fetchPriority="high" width={1200} height={673}/><figcaption><span>Art that changes a place.</span><span>Greetings from Cumberland / Maryland</span></figcaption></figure></section>
<section className="section work" id="work"><div className="section-heading"><div><p className="eyebrow">01 / Selected work</p><h2>Walls with<br/>something to say.</h2></div><p>A sense of place. A little personality.<br/>A reason to stop and look.</p></div><div className="portfolio">{site.projects.map(project=><figure key={project.slug}><div className="frame"><img src={project.image} alt={project.alt} loading="lazy"/></div><figcaption><div><h3>{project.title}</h3>{project.location&&<p>{project.location}</p>}</div><span>{project.category}</span></figcaption><p className="project-description">{project.description}</p></figure>)}</div></section>
<section className="section services"><p className="eyebrow">02 / What Marc paints</p><div className="services-layout"><h2>Your space.<br/>Your story.<br/><em>Painted big.</em></h2><div>{services.map(([x,href],i)=><Link href={href} key={x}><span className="service-number">0{i+1}</span>{x}<span aria-hidden="true">↗</span></Link>)}</div></div></section>
<section className="wall-cta"><div><p className="eyebrow">The best starting point? Your wall.</p><h2>Have a<br/>blank wall?</h2><p>Send Marc a photo of your space and tell him what you’re imagining. Measurements are optional.</p><CTA/></div><div className="wall-outline" aria-hidden="true"><span className="dim dim-w">W ?</span><span className="dim dim-h">H ?</span><span className="wall-plus">+</span><p>A little vision.<br/>A lot of possibility.</p><span className="wall-caption">Your next favorite place</span></div></section>
<section className="section process"><div className="section-heading"><div><p className="eyebrow">03 / From wall to wow</p><h2>Let’s make it happen.</h2></div><p>No perfect brief needed.<br/>Just a wall and a starting point.</p></div><ol>{steps.map(([x,d],i)=><li key={x}><span>0{i+1}</span><div><h3>{x}</h3><p>{d}</p></div></li>)}</ol></section>
<section className="section area"><p className="eyebrow">04 / Rooted here. Open to what’s next.</p><div className="area-layout"><h2>Western Maryland<br/><em>& a little beyond.</em></h2><div><p>Custom murals for spaces across Western Maryland and nearby regions. Projects farther afield are considered based on scope and availability.</p><div className="places">{site.serviceAreas.map(x=><span key={x}>{x}</span>)}</div><p className="muted">Surrounding Maryland, West Virginia & Pennsylvania areas.</p><CTA>Tell Marc where your wall is</CTA></div></div></section>
<section className="section about-preview"><blockquote><span aria-hidden="true">“</span>Good walls deserve <em>good stories.</em></blockquote><div><p className="eyebrow">05 / The artist behind the wall</p><h2>Meet Marc.</h2><p>{site.bio}</p><Link className="text-link" href="/about">More about Marc <span aria-hidden="true">↗</span></Link></div></section><FinalCTA/>
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"Person",name:site.name,jobTitle:"Mural artist",url:site.url,homeLocation:{"@type":"Place",name:"Western Maryland"}}).replace(/</g,"\\u003c")}}/>
</>}
