import Link from "next/link";
import {site} from "@/lib/content";
import {CTA,FinalCTA} from "@/components/shell";
export default function Home(){return <>
<section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="tiny-star">✳</span> A WALL IS JUST THE BEGINNING.</p><h1>Transform Your Wall Into Something People <em>Remember.</em></h1><div className="hero-bottom"><p>{site.subheading}</p><div className="hero-actions"><CTA/><Link className="text-link" href="#work">See the Work <span aria-hidden="true">↓</span></Link></div></div></div><figure className="hero-image"><img src={site.heroImage} alt="Greetings from Cumberland mural by Marc Phillips" fetchPriority="high"/><figcaption><span>ART THAT CHANGES A PLACE.</span><span>GREETINGS FROM CUMBERLAND / MARYLAND</span></figcaption></figure></section>
<section className="section work" id="work"><div className="section-heading"><div><p className="eyebrow">01 / SELECTED WORK</p><h2>Walls with<br/>something to say.</h2></div><p>A sense of place. A little personality.<br/>A reason to stop and look.</p></div><div className="portfolio">{site.projects.map(project=><figure key={project.slug}><img src={project.image} alt={project.alt} loading="lazy"/><figcaption><div><h3>{project.title}</h3>{project.location&&<p>{project.location}</p>}</div><span>{project.category.toUpperCase()}</span></figcaption><p className="project-description">{project.description}</p></figure>)}</div></section>
<section className="section services"><p className="eyebrow">02 / WHAT MARC PAINTS</p><div className="services-layout"><h2>Your space.<br/>Your story.<br/><em>Painted big.</em></h2><div>{["Commercial","Residential","Public Art","Restaurants & Hospitality","Schools / Organizations","Custom Projects"].map((x,i)=><Link href={i===0?"/commercial-murals":i===1?"/residential-murals":i===2?"/public-art":"/request"} key={x}><span className="service-number">0{i+1}</span>{x}<span aria-hidden="true">↗</span></Link>)}</div></div></section>
<section className="wall-cta"><div><p className="eyebrow">THE BEST STARTING POINT? YOUR WALL.</p><h2>Have a<br/>blank wall?</h2><p>Send Marc a photo of your space and tell him what you’re imagining.</p><CTA/></div><div className="wall-outline"><span aria-hidden="true">+</span><p>A little vision.<br/>A lot of possibility.</p><span className="wall-caption">YOUR NEXT FAVORITE PLACE</span></div></section>
<section className="section process"><div className="section-heading"><div><p className="eyebrow">03 / FROM WALL TO WOW</p><h2>Let’s make it happen.</h2></div><p>No perfect brief needed.<br/>Just a wall and a starting point.</p></div><ol>{["Show us your wall","Tell us your idea","Marc reviews the project","Discuss concept & quote","Bring it to life"].map((x,i)=><li key={x}><span>0{i+1}</span><h3>{x}</h3></li>)}</ol></section>
<section className="section area"><p className="eyebrow">04 / ROOTED HERE. OPEN TO WHAT’S NEXT.</p><div className="area-layout"><h2>Western Maryland<br/>& a little beyond.</h2><div><p>Custom murals for spaces across Western Maryland and nearby regions. Projects farther afield are considered based on scope and availability.</p><div className="places">{site.serviceAreas.map(x=><span key={x}>{x}</span>)}</div><p className="muted">Surrounding Maryland, West Virginia & Pennsylvania areas.</p><CTA>Tell Marc where your wall is</CTA></div></div></section>
<section className="section about-preview"><figure className="work-context"><img src="/cumberland-mural-in-context.jpg" alt="Greetings from Cumberland mural displayed indoors with a person standing in front" loading="lazy"/><figcaption>GREETINGS FROM CUMBERLAND / IN CONTEXT</figcaption></figure><div><p className="eyebrow">05 / THE ARTIST BEHIND THE WALL</p><h2>Meet Marc.</h2><p>{site.bio}</p><p className="placeholder-note">Biography placeholder — awaiting Marc’s approved story.</p><Link className="text-link" href="/about">More about Marc <span aria-hidden="true">↗</span></Link></div></section><FinalCTA/>
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"Person",name:site.name,jobTitle:"Mural artist",url:site.url,homeLocation:{"@type":"Place",name:"Western Maryland"}}).replace(/</g,"\u003c")}}/>
</>}
