"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {useForm,useWatch} from "react-hook-form";
import {zodResolver} from "@hookform/resolvers/zod";
import {requestSchema,projectTypes,budgets,timelines,type RequestValues} from "@/lib/schema";
type Photo={path:string;proof:string;type:"wall"|"inspiration";preview:string;name:string};
const titles=["Show us the wall.","Where is it?","Tell us about the wall.","What are you imagining?","What kind of project is this?","What’s your budget?","When are you thinking?","How can Marc reach you?","Looking good. Let’s review."];
const hints=["A photo is the best place to start. A few angles help, too.","Your city is enough. No exact street address needed.","A rough estimate is perfect. It’s okay if you don’t know.","No polished brief needed. Tell Marc what you have in mind.","Help Marc understand how the space will be used.","This is optional. A range helps shape the conversation, not an instant quote.","Share your ideal timing. Availability will be discussed with Marc.","Your details are only used to discuss your project.","Take one last look. You can go back and change anything."];
export default function RequestForm({token}:{token:string}){
 const [step,setStep]=useState(0),[photos,setPhotos]=useState<Photo[]>([]),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState(false);
 const heading=useRef<HTMLHeadingElement>(null);const previews=useRef<string[]>([]);useEffect(()=>()=>previews.current.forEach(URL.revokeObjectURL),[]);
 const {register,control,trigger,formState:{errors},handleSubmit}=useForm<RequestValues>({resolver:zodResolver(requestSchema),defaultValues:{customer_name:"",customer_email:"",customer_phone:"",preferred_contact:"email",city:"",state:"",zip:"",indoor_outdoor:"indoor",wall_width:"",wall_height:"",wall_dimensions_unknown:false,units:"feet",wall_material:"",notes:"",description:"",project_type:"Business",budget_range:"",timeline:"Just exploring",website:"",consent:false}});
 const v=useWatch({control}) as RequestValues;const unknown=v.wall_dimensions_unknown;
 async function upload(files:FileList|null,type:Photo["type"]){if(!files)return;setError("");if(!token){setError("The inquiry form is not connected yet. Please check back once project requests open.");return}if(photos.length+files.length>12){setError("You can add up to 12 photos in total.");return}setUploading(true);try{for(const file of Array.from(files)){const data=new FormData();data.append("file",file);data.append("token",token);const response=await fetch("/api/upload",{method:"POST",body:data});const result=await response.json();if(!response.ok)throw new Error(result.error);const preview=URL.createObjectURL(file);previews.current.push(preview);setPhotos(p=>[...p,{...result,type,preview,name:file.name}])}}catch(e){setError(e instanceof Error?e.message:"Upload failed. Try again.")}finally{setUploading(false)}}
 function move(n:number){setStep(n);setError("");requestAnimationFrame(()=>{heading.current?.focus();heading.current?.scrollIntoView({block:"start",behavior:"smooth"})})}
 async function next(){const fields: (keyof RequestValues)[][]=[[],["city","state","zip","indoor_outdoor"],["wall_width","wall_height","wall_dimensions_unknown","units"],["description"],["project_type"],["budget_range"],["timeline"],["customer_name","customer_email","customer_phone","preferred_contact"],[]];if(step===0&&!photos.some(x=>x.type==="wall")){setError("Add at least one photo of your wall to continue.");return}if(await trigger(fields[step]))move(step+1)}
 async function send(values:RequestValues){setBusy(true);setError("");try{const response=await fetch("/api/request",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({values,token,images:photos.map(({path,proof,type})=>({path,proof,type}))})});const result=await response.json();if(!response.ok)throw new Error(result.error);setSuccess(true);window.scrollTo({top:0,behavior:"smooth"})}catch(e){setError(e instanceof Error?e.message:"Something went wrong. Please try again.")}finally{setBusy(false)}}
 function field(name:keyof RequestValues,label:string,props:React.InputHTMLAttributes<HTMLInputElement>={}){return <div className="field"><label htmlFor={name}>{label}</label><input id={name} {...register(name)} {...props} aria-invalid={!!errors[name]} aria-describedby={errors[name]?`${name}-error`:undefined}/>{errors[name]&&<p className="field-error" id={`${name}-error`}>{errors[name]?.message}</p>}</div>}
 function options(name:"project_type"|"budget_range"|"timeline"|"indoor_outdoor"|"preferred_contact",items:readonly string[]){return <div className="choices">{items.map(x=><label className={v[name]===x?"choice selected":"choice"} key={x}><input type="radio" value={x} {...register(name)}/><span>{x===""?"Prefer to leave this open":x=== "indoor"?"Indoors":x==="outdoor"?"Outdoors":x==="email"?"Email":x==="phone"?"Phone":x}</span><span className="radio-mark" aria-hidden="true"/></label>)}</div>}
 function photoGrid(type:Photo["type"]){return <div className="photo-grid">{photos.filter(x=>x.type===type).map(p=><figure key={p.path}><img src={p.preview} alt={`Uploaded ${type} photo: ${p.name}`}/><button type="button" aria-label={`Remove ${p.name}`} onClick={()=>setPhotos(all=>all.filter(x=>x.path!==p.path))}>×</button></figure>)}</div>}
 function uploads(type:Photo["type"]){return <><div className="upload-box"><span className="upload-symbol" aria-hidden="true">＋</span><h3>{type==="wall"?"Every great mural starts here.":"A little inspiration helps."}</h3><p>JPG, PNG, or WebP · Up to 8 MB each · 12 photos total</p><div className="upload-actions"><label className="button">Choose photos<input className="file-input" type="file" multiple accept="image/jpeg,image/png,image/webp" disabled={uploading||!token} onChange={e=>{void upload(e.target.files,type);e.target.value=""}}/></label>{type==="wall"&&<label className="button secondary">Take a photo<input className="file-input" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" disabled={uploading||!token} onChange={e=>{void upload(e.target.files,type);e.target.value=""}}/></label>}</div></div>{photoGrid(type)}{uploading&&<p role="status">Uploading your photos…</p>}</>}
 if(success)return <section className="request-shell success"><p className="eyebrow">A NEW WALL. A NEW POSSIBILITY.</p><span className="big-star" aria-hidden="true">✳</span><h1>Marc’s got your wall.</h1><p>Your project has been sent. Marc will review your photos and details, then reach out using your contact information to discuss what’s possible.</p><Link href="/" className="button">Back to the site</Link></section>;
 return <div className="request-shell"><div className="request-top"><Link href="/" className="text-link">Back to the site</Link><span>YOUR WALL, REIMAGINED.</span></div><div className="progress-label"><p className="eyebrow">STEP {String(step+1).padStart(2,"0")} OF 09</p><span>{Math.round((step+1)/9*100)}%</span></div><div className="progress" role="progressbar" aria-label="Project request progress" aria-valuenow={step+1} aria-valuemin={1} aria-valuemax={9}><div style={{width:`${(step+1)/9*100}%`}}/></div><h1 ref={heading} tabIndex={-1}>{titles[step]}</h1><p className="step-hint">{hints[step]}</p>{!token&&<p className="setup-notice" role="status">Project requests are not open yet. You can explore the questions; photo uploads and submission will open once the site is connected.</p>}
 <form onSubmit={handleSubmit(send,()=>setError("Please go back and check the highlighted fields. Accept the privacy notice to submit."))}>
 <div className="honeypot" aria-hidden="true"><label>Website<input {...register("website")} tabIndex={-1} autoComplete="off"/></label></div>
 {step===0&&uploads("wall")}
 {step===1&&<><div className="field-grid">{field("city","City",{autoComplete:"address-level2"})}{field("state","State (two letters)",{autoComplete:"address-level1",maxLength:2,placeholder:"MD"})}{field("zip","ZIP code",{autoComplete:"postal-code",inputMode:"numeric"})}</div><fieldset><legend>Is the wall inside or outside?</legend>{options("indoor_outdoor",["indoor","outdoor"])}</fieldset></>}
 {step===2&&<><label className="check"><input type="checkbox" {...register("wall_dimensions_unknown")}/>I don’t know the dimensions.</label>{!unknown&&<div className="field-grid">{field("wall_width","Approximate width",{type:"number",min:"0.1",step:"any",inputMode:"decimal"})}{field("wall_height","Approximate height",{type:"number",min:"0.1",step:"any",inputMode:"decimal"})}<div className="field"><label htmlFor="units">Units</label><select id="units" {...register("units")}><option value="feet">Feet</option><option value="meters">Meters</option></select></div></div>}{field("wall_material","Wall / material type (optional)",{placeholder:"Brick, drywall, concrete…"})}<div className="field"><label htmlFor="notes">Anything else about the wall? (optional)</label><textarea id="notes" rows={3} {...register("notes")}/></div></>}
 {step===3&&<><div className="field"><label htmlFor="description">Your idea</label><textarea id="description" rows={6} placeholder="I’m imagining…" {...register("description")} aria-invalid={!!errors.description}/>{errors.description&&<p className="field-error">{errors.description.message}</p>}</div><p className="example-text">Local landmarks · Abstract · Nature · Company branding · Children’s room · Sports · Something completely custom</p><h3 className="inspiration-title">Inspiration photos (optional)</h3>{uploads("inspiration")}</>}
 {step===4&&<fieldset><legend className="sr-only">Project type</legend>{options("project_type",projectTypes)}</fieldset>}
 {step===5&&<fieldset><legend className="sr-only">Budget range, optional</legend>{options("budget_range",[...budgets,""])}</fieldset>}
 {step===6&&<fieldset><legend className="sr-only">Timeline</legend>{options("timeline",timelines)}</fieldset>}
 {step===7&&<>{field("customer_name","Your name",{autoComplete:"name"})}{field("customer_email","Email",{type:"email",autoComplete:"email"})}{field("customer_phone","Phone (optional unless preferred)",{type:"tel",autoComplete:"tel"})}<fieldset><legend>Preferred contact method</legend>{options("preferred_contact",["email","phone"])}</fieldset></>}
 {step===8&&<div className="review"><section><div className="review-heading"><h2>Your wall</h2><button type="button" onClick={()=>move(0)}>Edit photos</button></div><div className="photo-grid">{photos.filter(x=>x.type==="wall").map(x=><img key={x.path} src={x.preview} alt="Your uploaded wall"/>)}</div></section><section><div className="review-heading"><h2>The project</h2><button type="button" onClick={()=>move(1)}>Edit details</button></div><dl><dt>Location</dt><dd>{v.city}, {v.state.toUpperCase()} {v.zip} · {v.indoor_outdoor}</dd><dt>Wall</dt><dd>{v.wall_dimensions_unknown?"Dimensions unknown":`${v.wall_width} × ${v.wall_height} ${v.units}`}{v.wall_material&&` · ${v.wall_material}`}</dd>{v.notes&&<><dt>Wall notes</dt><dd>{v.notes}</dd></>}<dt>Your idea</dt><dd>{v.description}</dd><dt>Project type</dt><dd>{v.project_type}</dd><dt>Budget</dt><dd>{v.budget_range||"Not provided"}</dd><dt>Timeline</dt><dd>{v.timeline}</dd></dl>{photos.some(x=>x.type==="inspiration")&&<><h3>Inspiration</h3><div className="photo-grid">{photos.filter(x=>x.type==="inspiration").map(x=><img key={x.path} src={x.preview} alt="Your uploaded inspiration"/>)}</div></>}</section><section><div className="review-heading"><h2>Your contact details</h2><button type="button" onClick={()=>move(7)}>Edit contact</button></div><p>{v.customer_name}<br/>{v.customer_email}<br/>{v.customer_phone}</p><p>Preferred contact: {v.preferred_contact}</p></section><label className="check"><input type="checkbox" {...register("consent")}/><span>I agree to share these details and photos with Marc to discuss my mural project. <Link href="/privacy" target="_blank">Privacy notice</Link></span></label>{errors.consent&&<p className="field-error">{errors.consent.message}</p>}</div>}
 {error&&<p className="form-error" role="alert">{error}</p>}
 <div className="form-actions">{step>0&&<button type="button" className="back-button" disabled={busy||uploading} onClick={()=>move(step-1)}>Back</button>}{step<8?<button type="button" className="button" disabled={uploading} onClick={()=>void next()}>{step===5?"Continue (budget optional)":"Continue"}<span aria-hidden="true">↗</span></button>:<button className="button" type="submit" disabled={busy||!token}>{busy?"Sending your project…":"Send My Project to Marc"}</button>}</div><p className="form-footnote">Your photos stay private. Your idea stays yours.</p>
 </form></div>
}
