export const site = {
 name: "Marc Phillips", artistSlug: "marc-phillips", artistId: "b76b7a25-b062-42c8-8dc6-a474bcc2a730",
 url: process.env.NEXT_PUBLIC_SITE_URL || (process.env.NODE_ENV === "production" ? "https://mural-me.vercel.app" : "http://localhost:3000"),
 hero: "Transform Your Wall Into Something People Remember.",
 subheading: "Custom murals by Western Maryland artist Marc Phillips.",
 cta: "Show Marc Your Wall", email: "", phone: "", socialLinks: [] as {label:string;url:string}[],
 bio: "Marc Phillips is a mural artist based around Western Maryland and Cumberland, MD. A fuller biography, written and approved by Marc, will be added here.",
 bioPlaceholder: true, profileImage: "",
 serviceAreas: ["Cumberland, MD", "Frostburg, MD", "Hagerstown, MD", "Morgantown, WV"],
 responseTime: "", heroImage: "/greetings-from-cumberland.jpg",
 projects: [{slug:"greetings-from-cumberland",title:"Greetings from Cumberland",location:"Cumberland, Maryland",category:"Mural",image:"/greetings-from-cumberland.jpg",alt:"Greetings from Cumberland mural by Marc Phillips, with local landmarks and businesses illustrated inside large postcard-style letters",description:"A postcard-style mural celebrating Cumberland through local landmarks, businesses, and bold hand-painted lettering.",images:[{src:"/greetings-from-cumberland.jpg",alt:"Full view of Greetings from Cumberland mural"},{src:"/cumberland-mural-in-context.jpg",alt:"Greetings from Cumberland mural shown in its interior setting"}]}],
};
export const landingPages: Record<string,{title:string;eyebrow:string;intro:string;sections:{title:string;text:string}[]}> = {
 "commercial-murals": {title:"Give your business a wall worth remembering.",eyebrow:"Commercial murals",intro:"A custom mural can welcome customers, tell your story, or give a space a distinct identity. Start with a photo of your wall and an idea of what it needs to do.",sections:[{title:"Make the space work for you",text:"Share how people use the space, your brand guidelines, and where the mural will be seen. A storefront, office, or restaurant each asks for a different approach."},{title:"Plan around your business",text:"Mention opening hours, access restrictions, and your preferred installation window. Surface preparation, wall size, and access all shape the scope and quote."}]},
 "residential-murals": {title:"Make a room unmistakably yours.",eyebrow:"Residential murals",intro:"From a quiet nature-inspired wall to a playful children’s room, a mural can change the feeling of a home. Share the room, the wall, and what you imagine living with.",sections:[{title:"Think about the whole room",text:"Photos showing furniture, light, and adjacent walls help explain your space. You can include colors or inspiration images, even if your idea is still taking shape."},{title:"A few practical details",text:"Tell Marc whether the wall is indoors or outdoors, its approximate size, and any texture or existing finish. Exact measurements can be discussed later."}]},
 "public-art": {title:"A shared wall. A shared sense of place.",eyebrow:"Public art murals",intro:"Public murals can connect a place with the people who use it. Tell Marc about your community, your site, and the story you want to explore.",sections:[{title:"Start with the people and the place",text:"Include the project organizer, intended audience, and themes that matter locally. Community input and approval requirements are helpful to identify early."},{title:"Check permissions and access",text:"Confirm who owns the wall and whether approvals, permits, or access equipment may be needed. Share any funding or scheduling constraints with your inquiry."}]},
 "cumberland-md": {title:"A new story for your Cumberland wall.",eyebrow:"Cumberland, Maryland",intro:"Based around Western Maryland and Cumberland, Marc Phillips welcomes custom mural inquiries for businesses, homes, and community spaces.",sections:[{title:"From an empty wall to an idea",text:"Send photos taken from a few angles. Include the neighborhood or city, whether the wall is inside or outside, and what you would like the mural to bring to the space."},{title:"Plan for your site",text:"Outdoor surface condition, weather exposure, and access can affect a mural project. A photo and approximate dimensions make the first conversation more useful."}]},
 "morgantown-wv": {title:"Something memorable for your Morgantown space.",eyebrow:"Morgantown, West Virginia",intro:"Marc considers mural projects in Morgantown and surrounding West Virginia areas. Share your location and scope so travel and availability can be discussed.",sections:[{title:"Show the setting",text:"Whether it is a hospitality space, home, or community wall, include photos of the wall and its surroundings. Explain who will see it and the mood or story you have in mind."},{title:"Talk through the logistics",text:"Include your timeline, approximate size, and any access limitations. Travel, preparation, and scheduling will be considered before a concept and quote are agreed."}]},
};
