import type {Metadata} from "next";
import Link from "next/link";
import {notFound} from "next/navigation";
import {site,landingPages,imageAlt} from "@/lib/content";
import {CTA,FinalCTA} from "@/components/shell";
export function generateStaticParams(){return [...Object.keys(landingPages),"about","privacy"].map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=landingPages[slug];return {title:p?.eyebrow|| (slug==="about"?"About Marc":"Privacy"),description:p?.intro||(slug==="about"?site.bio:"How mural inquiry details and photos are stored and used."),alternates:{canonical:`/${slug}`},openGraph:{url:`/${slug}`,title:p?.title||(slug==="about"?"Meet Marc Phillips":"Privacy")}}}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;
if(slug==="privacy")return <article className="section article"><p className="eyebrow">Your information</p><h1>Privacy, simply.</h1><p>When you submit a mural inquiry, your contact details, project information, and uploaded photos are stored privately and used to review and discuss your project. Please do not upload sensitive personal information or photos you do not have permission to share.</p><h2>Who receives your request</h2><p>Marc and authorized site administrators can access inquiries. Supabase stores the data and photos; the configured email service delivers lead notifications. Submitted photos are never published in the portfolio.</p><h2>Requesting removal</h2><p>{site.email?<>Email <a href={`mailto:${site.email}`}>{site.email}</a></>:<>Reply to your project correspondence</>} to request correction or deletion of your details and photos. Requests are retained only while needed to discuss and manage a project.</p></article>;
if(slug==="about")return <><article className="section about-page"><div className="about-intro"><p className="eyebrow">Mural artist / Western Maryland</p><h1>Meet Marc <em>Phillips.</em></h1><p className="lede">{site.bio}</p><CTA/></div><div className="about-work">{site.projects.map(x=><figure key={x.slug}><img src={x.images[0].src} alt={x.images[0].alt} loading="lazy"/><figcaption>{x.title}</figcaption></figure>)}</div></article>
<section className="section about-areas"><p className="eyebrow">Where Marc works</p><div className="places">{site.serviceAreas.map(x=><span key={x}>{x}</span>)}</div><p className="muted">Plus surrounding Maryland, West Virginia & Pennsylvania areas. <Link className="inline-link" href="/#work">See selected work</Link>.</p></section><FinalCTA/></>;
const p=landingPages[slug];if(!p)notFound();return <><article className="section article"><p className="eyebrow">{p.eyebrow}</p><h1>{p.title}</h1><p className="intro">{p.intro}</p><CTA/><figure className="article-figure"><img src={p.image} alt={imageAlt(p.image)}/></figure><div className="article-sections">{p.sections.map((x,i)=><section key={x.title}><span className="service-number">0{i+1}</span><h2>{x.title}</h2><p>{x.text}</p></section>)}</div><aside className="article-callout"><h2>Start with a wall photo.</h2><p>You do not need an exact address or a finished design. Send your city, a few photos, and whatever you know about the project. Marc will review the details before discussing a concept and quote.</p><CTA/></aside></article><FinalCTA/></>}
