import type {Metadata} from "next";
import Link from "next/link";
import {notFound} from "next/navigation";
import {primaryArtist as a,landingPages,imageAlt,projectsBy,fill} from "@/lib/content";
import {CTA,FinalCTA} from "@/components/shell";
export function generateStaticParams(){return [...Object.keys(landingPages),"about","privacy"].map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=landingPages[slug];return {title:p?.eyebrow|| (slug==="about"?`About ${a.firstName}`:"Privacy"),description:p?fill(p.intro,a):(slug==="about"?a.bio:"How mural inquiry details and photos are stored and used."),alternates:{canonical:`/${slug}`},openGraph:{url:`/${slug}`,title:p?.title||(slug==="about"?`Meet ${a.name}`:"Privacy")}}}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;
if(slug==="privacy")return <article className="section article"><p className="eyebrow">Your information</p><h1>Privacy, simply.</h1><p>When you submit a mural inquiry, your contact details, project information, and uploaded photos are stored privately and used to review and discuss your project. Please do not upload sensitive personal information or photos you do not have permission to share.</p><h2>Who receives your request</h2><p>The artist you contact and authorized site administrators can access inquiries. Supabase stores the data and photos; the configured email service delivers lead notifications. Submitted photos are never published in the portfolio.</p><h2>Requesting removal</h2><p>{a.email?<>Email <a href={`mailto:${a.email}`}>{a.email}</a></>:<>Reply to your project correspondence</>} to request correction or deletion of your details and photos. Requests are retained only while needed to discuss and manage a project.</p></article>;
if(slug==="about")return <><article className="section about-page"><div className="about-intro"><p className="eyebrow">{a.role} / {a.region}</p><h1>Meet {a.firstName} <em>{a.name.slice(a.firstName.length+1)}.</em></h1><p className="lede">{a.bio}</p><CTA/>{a.profileImage&&<figure className="portrait"><img src={a.profileImage} alt={`${a.name} in front of his Greetings from Cumberland mural`} style={{objectPosition:a.portraitFocus}}/><figcaption>{a.name}</figcaption></figure>}</div><div className="about-work">{projectsBy(a.id).map(x=><figure key={x.slug} className="card"><img src={x.images[0].src} alt={x.images[0].alt} width={x.images[0].width} height={x.images[0].height} loading="lazy"/><figcaption><Link className="stretched" href={`/work/${x.slug}`}>{x.title}</Link></figcaption></figure>)}</div></article>
<section className="section about-areas"><p className="eyebrow">Where {a.firstName} works</p><div className="places">{a.serviceAreas.map(x=><span key={x}>{x}</span>)}</div><p className="muted">Plus {a.serviceAreaNote.charAt(0).toLowerCase()+a.serviceAreaNote.slice(1)} <Link className="inline-link" href="/#work">See selected work</Link>.</p></section><FinalCTA/></>;
const p=landingPages[slug];if(!p)notFound();return <><article className="section article"><p className="eyebrow">{p.eyebrow}</p><h1>{p.title}</h1><p className="intro">{fill(p.intro,a)}</p><CTA/><figure className="article-figure"><img src={p.image} alt={imageAlt(p.image)}/></figure><div className="article-sections">{p.sections.map((x,i)=><section key={x.title}><span className="service-number">0{i+1}</span><h2>{x.title}</h2><p>{fill(x.text,a)}</p></section>)}</div><aside className="article-callout"><h2>Start with a wall photo.</h2><p>You do not need an exact address or a finished design. Send your city, a few photos, and whatever you know about the project. {a.firstName} will review the details before discussing a concept and quote.</p><CTA/></aside></article><FinalCTA/></>}
