import type {Metadata} from "next";
import {notFound} from "next/navigation";
import {site,landingPages} from "@/lib/content";
import {CTA,FinalCTA} from "@/components/shell";
export function generateStaticParams(){return [...Object.keys(landingPages),"about","privacy"].map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=landingPages[slug];return {title:p?.eyebrow|| (slug==="about"?"About Marc":"Privacy"),description:p?.intro,alternates:{canonical:`/${slug}`},openGraph:{url:`/${slug}`,title:p?.title||"Marc Phillips"}}}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;
if(slug==="privacy")return <article className="section article"><p className="eyebrow">YOUR INFORMATION</p><h1>Privacy, simply.</h1><p>When you submit a mural inquiry, your contact details, project information, and uploaded photos are stored privately and used to review and discuss your project. Please do not upload sensitive personal information or photos you do not have permission to share.</p><h2>Who receives your request</h2><p>Marc and authorized site administrators can access inquiries. Supabase stores the data and photos; the configured email service delivers lead notifications. Submitted photos are not published in the portfolio.</p><h2>Requesting removal</h2><p>Use the contact details in your project correspondence to request correction or deletion. Requests are retained while needed to discuss and manage a project. This policy must be reviewed and contact details completed before launch.</p></article>;
if(slug==="about")return <><article className="section article"><p className="eyebrow">MURAL ARTIST / WESTERN MARYLAND</p><h1>Meet Marc Phillips.</h1><p>{site.bio}</p><p className="placeholder-note">Approved biography coming soon. No experience, awards, or client claims have been added.</p><CTA/></article><FinalCTA/></>;
const p=landingPages[slug];if(!p)notFound();return <><article className="section article"><p className="eyebrow">{p.eyebrow}</p><h1>{p.title}</h1><p className="intro">{p.intro}</p><CTA/><img className="article-image" src={site.heroImage} alt="Greetings from Cumberland mural by Marc Phillips"/>{p.sections.map(x=><section key={x.title}><h2>{x.title}</h2><p>{x.text}</p></section>)}<h2>Start with a wall photo.</h2><p>You do not need an exact address or a finished design. Send your city, a few photos, and whatever you know about the project. Marc will review the details before discussing a concept and quote.</p></article><FinalCTA/></>}
