import {allow} from "@/lib/rate-limit";
import {NextResponse} from "next/server";
import {z} from "zod";
import {requestSchema,imageSchema} from "@/lib/schema";
import {db,bucket} from "@/lib/supabase";
import {sameOrigin,verifyTicket,sign,equal} from "@/lib/security";
import {notifyLead} from "@/lib/email";
import {site} from "@/lib/content";
const submission=z.object({values:requestSchema,token:z.string(),images:z.array(imageSchema.extend({proof:z.string()})).min(1).max(12)});
export async function POST(req:Request){if(!sameOrigin(req))return NextResponse.json({error:"Invalid origin."},{status:403});if(Number(req.headers.get("content-length")||0)>25000)return NextResponse.json({error:"Request is too large."},{status:413});try{if(!await allow(req,"request",10,3600))return NextResponse.json({error:"Too many attempts. Please try again later."},{status:429});const parsed=submission.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:"Please review the required project details."},{status:400});const {values:v,token,images}=parsed.data;const id=verifyTicket(token);if(!id||!images.some(x=>x.type==="wall")||images.some(x=>!x.path.startsWith(`${id}/`)||!equal(sign(x.path),x.proof)))return NextResponse.json({error:"Please refresh and upload your wall photos again."},{status:400});const client=db();const {data:prior,error:priorError}=await client.from("project_requests").select("id").eq("id",id).maybeSingle();if(priorError)throw priorError;if(prior)return NextResponse.json({ok:true});
const {website:honeypot,consent,units,notes,wall_width,wall_height,...rest}=v;void honeypot;void consent;
const lead={...rest,id,assigned_artist_id:site.artistId,wall_width:v.wall_dimensions_unknown?null:Number(wall_width),wall_height:v.wall_dimensions_unknown?null:Number(wall_height),wall_units:units,wall_notes:notes,status:"new"};
const {error}=await client.rpc("submit_project_request",{lead,images:images.map(x=>({image_url:x.path,image_type:x.type}))});if(error){if(error.code==="23505")return NextResponse.json({ok:true});throw error}
try{const urls=await Promise.all(images.map(async x=>{const {data,error}=await client.storage.from(bucket).createSignedUrl(x.path,7*86400);if(error)throw error;return `${x.type}: ${data.signedUrl}`}));await notifyLead({to:process.env.LEAD_NOTIFICATION_EMAIL||site.email,subject:`New mural inquiry: ${v.customer_name} / ${v.city}`,text:[`Name: ${v.customer_name}`,`Email: ${v.customer_email}`,`Phone: ${v.customer_phone||"Not provided"}`,`Preferred contact: ${v.preferred_contact}`,`Location: ${v.city}, ${v.state} ${v.zip}`,`Setting: ${v.indoor_outdoor}`,`Project: ${v.project_type}`,`Budget: ${v.budget_range||"Not provided"}`,`Timeline: ${v.timeline}`,`Dimensions: ${v.wall_dimensions_unknown?"Unknown":`${wall_width} × ${wall_height} ${units}`}`,`Material: ${v.wall_material||"Unknown"}`,`Notes: ${notes}`,`Idea: ${v.description}`,`Private photo links (expire in 7 days):`,...urls,`Lead inbox: ${site.url}/admin`].join("\n")});await client.from("project_requests").update({notification_status:"sent"}).eq("id",id)}catch{console.error("Lead saved; notification delivery failed.",id);await client.from("project_requests").update({notification_status:"failed"}).eq("id",id)}
return NextResponse.json({ok:true})}catch{ return NextResponse.json({error:"Your request could not be saved. Please try again."},{status:503})}}
